version: '3'

services:
  front:
    build:
      context: front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app/front
    network_mode: host
    env_file:
      - ./front/.env
  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - ./server:/app/server
    env_file:
      - ./server/.env
